config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users do
    resources :pictures do
      resources :associations
    end
  end

  resources :pictures do
    resources :tags
    resources :associations
  end
  root to: "users#index"
end

app/models/absorption.rb
class Absorption < ApplicationRecord
  belongs_to :picture
  belongs_to :tag

  validates :tag_id, :picture_id, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association.rb
class Association < ApplicationRecord
  belongs_to :picture
  belongs_to :user

  validates :user_id, :picture_id, :typification, :presence => true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :absorptions
  has_many :tags, through: :absorptions
  has_many :associations
  has_many :users, through: :associations

  has_attached_file :image,
  # url: "/system/:hash.:extension",
  # hash_secret: "abc123",
                  styles: { original: ["922x922>", :jpg],
                            thumb: ["100x100>", :jpg]},
                  convert_options: {
                    thumb: "-quality 100 -strip",
                    original: "-quality 100 -strip" }




  validates_attachment :image,
        presence: true,
        content_type: {
          content_type: ["image/jpeg", "image/gif", "image/png"]
        },
       size: { in: 0..3.megabytes }

# def tags
#   returned_tags = []
#   Tag.all.each do |tag|
#     if tag.picture_id === self.id
#      returned_tags.push(tag)
#     end
#   end
#   returned_tags
# end


end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :absorptions
  has_many :pictures, through: :absorptions

  validates :name, :presence => true




end

app/models/user.rb
class User < ApplicationRecord
  has_many :associations
  has_many :pictures, through: :associations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  validates :email, :encrypted_password, :avatar_url, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :is_admin?





end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, :only => [:add, :delete]


  def index
    @pictures = Picture.order('created_at')
    @id = current_user.id
  end

  def show
    @users = User.all  #for tagging other users
    @user = current_user
    @picture = Picture.find(params[:id])
    @association = Association.new
    @tag = @picture.tags.new

  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @user = User.find(current_user.id)
    if @picture.save
      this_user_id = current_user.id
      this_picture_id = @picture.id
      @association = Association.new(:user_id => this_user_id, :picture_id => this_picture_id)
      @association.save
      flash[:notice] = "Picture successfully added!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Picture save failed!"
      render :new
    end
  end

  # def edit
  #   @picture = Picture.find(params[:id])
  # end
  #
  # def update
  #   @picture = Picture.find(params[:id])
  #   if @picture.update(picture_params)
  #     flash[:notice] = "Picture successfully edited!"
  #     redirect_to pictures_path
  #   else
  #     flash[:alert] = "Picture edit failed!"
  #     render :edit
  #   end
  # end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:notice] = "Picture successfully deleted!"
    redirect_to pictures_path
  end

private
  def picture_params
    params.require(:picture).permit(:image)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def create
    @picture = Picture.find(params[:picture_id])
    @tag = Tag.new(tag_params)
    # @tag = @picture.tags.build(tag_params)
    @tag.picture_id = @picture.id

    if @tag.save
      flash[:notice] = "Tag successfully added!"
      redirect_to picture_path(@picture)
    else
      flash[:alert] = "Tag save failed!"
      redirect_to picture_path(@picture)
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:notice] = "Tag successfully edited!"
      redirect_to tags_path
    else
      flash[:alert] = "Tag edit failed!"
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash[:notice] = "Tag successfully deleted!"
    redirect_to tags_path
  end

private
  def tag_params
    params.require(:tag).permit(:name, :picture_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @pictures = Picture.all
  end

  def show
    @user = User.find(params[:id])
    @logged_user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlikrClone</title>
    <%= csrf_meta_tags %>
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron">
      <h1><%= link_to "Flickr Clone", root_path %></h1>
      <% if current_user %>
      <p>
        User: <%= current_user.email %> | <%= link_to "Sign out", destroy_user_session_path, method: 'delete' %>
      </p>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pictures/_picture.html.erb
<div>
  <%= link_to image_tag(picture.image.url(:thumb), class: 'media-object'), picture_path(picture) %>
  <h4>Picture #: <%= picture.id %></h4>
</div>

app/views/pictures/index.html.erb
<div class="page-header">
  <h1>Photos</h1>
</div>
<%= render @pictures %>


<!-- <ul>
  <% @pictures.each do |picture| %>
    <li><%= picture.id %></li>


  <% end %>
</ul> -->

app/views/pictures/new.html.erb
<div class="page-header"><h1>Upload Picture</h1></div>

<%= form_for @picture do |f| %>
  <%= render 'layouts/errors', object: @picture %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/pictures/show.html.erb
<h1><%= image_tag(@picture.image.url, class: 'media-object') %></h1>
<h2>Posted by: </h2>

<p><%= link_to "Return to pictures", pictures_path %></p>

<h2>Tagged Users</h2>

<hr>
<h4>Tag another User</h4>
<%= form_for [@picture, @association] do |f| %>
<%= f.label :user_id %>
<%= f.select :user_id,
[@users.each do |user|
  ["#{user.email}","#{user.email}"]
end
]
%>
<p><%= f.submit %></p>
<% end %>

<hr>
<h2>Picture Tags</h2>
<% if Tag.where(picture_id: @picture.id) != 0 %>
  <% Tag.where(picture_id: @picture.id).each do |tag| %>
    <%= tag.name %>
  <% end %>
<% else %>
  <p> No tags for this photo</p>
<% end %>
<hr>


<h4>Add a tag</h4>
<%= form_for [@picture, @tag] do |f| %>
<!-- <%= f.hidden_field :picture_id, value: @picture.id %> -->
<%= f.label :name %>
<%= f.text_field :name %>
<p><%= f.submit %></p>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Users</h1>
    <ul>
      <% @users.each do |user| %>
        <li>
          <%= link_to user.email, user_path(user) %>(<%= user.name %>)
        </li>
      <% end %>
    </ul>



  </div>
  <div class="col-md-8">
    <h1>Pictures</h1>
    <div class="row inline">
      <% @pictures.each do |picture| %>
        <%= image_tag(picture.image.url(:thumb), class: 'media-object') %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.email %>
<%= @user.name %>
<% if @user == @logged_user %>
  <%= link_to "New Picture", new_picture_path %>
<% end %>

<% if @user.admin == true %>
<p>Show this text only to admins</p>
<% end %>

<h1>My Photos:</h1>
<!-- Users' own photos -->
<% @user.pictures.each do |picture| %>
  <%= link_to image_tag(picture.image.url(:thumb), class: 'media-object'), picture_path(picture) %>
  <% if @user == @logged_user %>
    <%= link_to 'Remove', picture_path(picture), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
  <br><br>
<% end %>

<br>
<hr>
<br>

<!-- ADD:
Favorites
Tagged Photos -->
<h1>My Favorite Photos</h1>
<p>WIP</p>
<hr>
<h1>My Tagged Photos</h1>
<p>WIP</p>